export const PERMISSIONS = Object.freeze({
  USER_FREEZE: "USER_FREEZE",
  USER_UNFREEZE: "USER_UNFREEZE",
  KYC_APPROVE: "KYC_APPROVE",
  KYC_REJECT: "KYC_REJECT",
  WALLET_ADJUST: "WALLET_ADJUST",
  VIEW_TRANSACTIONS: "VIEW_TRANSACTIONS",
  ADD_FRAUD_NOTE: "ADD_FRAUD_NOTE",
  VIEW_FRAUD_NOTES: "VIEW_FRAUD_NOTES",
  MANAGE_ADMINS: "MANAGE_ADMINS"
});

export const ADMIN_PERMISSIONS = {
  FOUNDER_ADMIN: Object.values(PERMISSIONS),

  COMPLIANCE_ADMIN: [
    PERMISSIONS.USER_FREEZE,
    PERMISSIONS.USER_UNFREEZE,
    PERMISSIONS.KYC_APPROVE,
    PERMISSIONS.KYC_REJECT,
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.ADD_FRAUD_NOTE,
    PERMISSIONS.VIEW_FRAUD_NOTES
  ],

  SUPPORT_ADMIN: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.VIEW_FRAUD_NOTES,
    PERMISSIONS.ADD_FRAUD_NOTE
  ]
};